
name: mice_activeg
description: "Sherpa Voice Recorder."
publish_to: 'none' # Prevents accidental publication to pub.dev

version: 1.1.8+32

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  flutter_sound:
  record:
  permission_handler:
  wakelock_plus:
  flutter_timer_countdown:
  shared_preferences:
  get:
  path_provider:
  dio:
  internet_connection_checker:
  flutter_foreground_task:
  flutter_background_service:
  connectivity_plus:
  firebase_core:
  firebase_analytics:
  onesignal_flutter: ^5.3.3
  flutter_local_notifications:
  hive:
  hive_flutter:

  image_picker:
  file_picker:
  video_player:
  battery_plus:
  firebase_performance:
  intl:
  dots_indicator:
  web_socket_channel:
  omni_datetime_picker:
  sqflite:
  path:
  http:
  flutter_svg:
  flutter_markdown:
  fl_chart: ^1.0.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  photo_view: ^0.14.0
  logger: ^2.0.2+1
  fluttertoast:
    git:
      url: https://github.com/MarlonJD/FlutterToast.git
      ref: patch-1


#  aws_client: ^0.7.0


#  speech_to_text: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "asset/images/newlogo.png"
  remove_alpha_ios: false

flutter:
  uses-material-design: true
  fonts:
    - family: Manrope
      fonts:
        - asset: asset/fonts/manrope-regular.otf
          weight: 400
        - asset: asset/fonts/manrope-semibold.otf
          weight: 600
        - asset: asset/fonts/manrope-bold.otf
          weight: 700
    - family: Inter
      fonts:
        - asset: asset/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: asset/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: asset/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
  assets:
    - asset/images/
    - asset/icons/







